version: "3"
services:
  redis:
    image: redis
  app:
    links:
      - redis
    depends_on:
      - redis
    container_name: finddoc-backend
    restart: always
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
